const VERBFORMS = {
  become: ["become", "becomes", "became", "becoming"],
  be: ["be", "am", "is", "are", "was", "were", "been", "being"],
  begin: ["begin", "begins", "began", "begun", "beginning"],
  blow: ["blow", "blows", "blew", "blown", "blowing"],
  bring: ["bring", "brings", "brought", "bringing"],
  build: ["build", "builds", "built", "building"],
  burn: ["burn", "burns", "burned", "burnt", "burning"],
  buy: ["buy", "buys", "bought", "buying"],
  catch: ["catch", "catches", "caught", "catching"],
  choose: ["choose", "chooses", "chose", "chosen", "choosing"],
  come: ["come", "comes", "came", "coming"],
  cut: ["cut", "cuts", "cutting"],
  do: ["do", "does", "did", "done", "doing"],
  drink: ["drink", "drinks", "drank", "drunk", "drinking"],
  eat: ["eat", "eats", "ate", "eaten", "eating"],
  feel: ["feel", "feels", "felt", "felt", "feeling"],
  fight: ["fight", "fights", "fought", "fighting"],
  find: ["find", "finds", "found", "finding"],
  fly: ["fly", "flies", "flew", "flown", "flying"],
  forget: ["forget", "forgets", "forgot", "forgotten", "forgetting"],
  get: ["get", "gets", "got", "gotten", "getting"],
  give: ["give", "give", "gives", "gave", "given", "giving"],
  go: ["go", "goes", "went", "gone", "going"],
  grow: ["grow", "grows", "grew", "grown", "growing"],
  have: ["have", "has", "had", "having"],
  hear: ["hear", "hears", "heard", "hearing"],
  hit: ["hit", "hits", "hitting"],
  hold: ["hold", "holds", "held", "holding"],
  hurt: ["hurt", "hurts", "hurting"],
  keep: ["keep", "keeps", "kept", "keeping"],
  know: ["know", "knows", "knew", "known", "knowing"],
  lead: ["lead", "leads", "led", "leading"],
  leave: ["leave", "leaves", "left", "leaving"],
  lend: ["lend", "lends", "lent", "lending"],
  lie: ["lie", "lies", "lay", "lain", "lying"],
  lose: ["lose", "loses", "lost", "losing"],
  make: ["make", "makes", "made", "making"],
  mean: ["mean", "means", "meant", "meaning"],
  meet: ["meet", "meets", "met", "meeting"],
  put: ["put", "puts", "put", "putting"],
  read: ["read", "reads", "reading"],
  ride: ["ride", "rides", "rode", "ridden", "riding"],
  ring: ["ring", "rings", "rang", "rung", "ringing"],
  run: ["run", "runs", "ran", "running"],
  say: ["say", "says", "said", "saying"],
  see: ["see", "sees", "saw", "seen", "seeing"],
  sell: ["sell", "sells", "sold", "selling"],
  send: ["send", "sends", "sent", "sending"],
  shake: ["shake", "shakes", "shook", "shaken", "shaking"],
  show: ["show", "shows", "showed", "shown", "showing"],
  shut: ["shut", "shuts", "shut", "shutting"],
  sing: ["sing", "sings", "sang", "sung", "singing"],
  sit: ["sit", "sits", "sat", "sitting"],
  sleep: ["sleep", "sleeps", "slept", "sleeping"],
  smell: ["smell", "smells", "smelled", "smelt", "smelling"],
  speak: ["speak", "speaks", "spoke", "spoken", "speaking"],
  spend: ["spend", "spends", "spent", "spending"],
  stand: ["stand", "stands", "stood", "standing"],
  swim: ["swim", "swims", "swam", "swum", "swimming"],
  take: ["take", "takes", "took", "taken", "taking"],
  teach: ["teach", "teaches", "taught", "teaching"],
  tell: ["tell", "tells", "told", "telling"],
  think: ["think", "thinks", "thought", "thinking"],
  throw: ["throw", "throws", "threw", "thrown", "throwing"],
  understand: ["understand", "understands", "understood", "understanding"],
  wear: ["wear", "wears", "wore", "worn", "wearing"],
  win: ["win", "wins", "won", "winning"],
  write: ["write", "writes", "wrote", "written", "writing"]
};

export default VERBFORMS;
